---
  - name: Provision 2 EC2 Instances
    hosts: localhost
    connection: local
    gather_facts: False
    tags: provisioning
    roles:
      - ec2_visual
      - ec2_web

  - name: Install & Configure Elasticsearch & Kibana
    hosts: visualserver
    become: yes
    gather_facts: True
    tags: Installation & Configuration
    roles: 
      - es
      - kibana

  - name: Install & configure, httpd & metricbeat 
    hosts: webserver
    become: yes
    gather_facts: False
    tags: Installation & Configuration (httpd & Metricbeat)
    roles: 
      - metricbeat_httpd

  - name: Import Kibana Dashboard
    hosts: localhost
    gather_facts: True
    tags: Kibana Visualisation
    roles:
      - kibana_import_visual